spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS staby_connect
      username: sa
      password:

  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size : 100

    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true


  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: false
